- menu_name: "Servicios"

- name: "Contacto"
  url: "/contacto/"
  title: "Contacto"

- name: "RSS"
  url: "/feed.xml"
  title: "Suscríbete al Feed RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Suscríbete al Feed Atom"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap para Google Webmaster Tools"
